<?php
/**
 * @file
 * Provides install, upgrade and un-install functions for menu_block.
 */

/**
 * Implements hook_install().
 */
function menu_block_install() {
  $config = config('menu_block.settings');
  $config->set('menu_block_menu_order', array('main-menu' => '', 'user-menu' => ''));
  $config->save();
}
  
/**
 * Implements hook_update_last_removed().
 */
function menu_block_update_last_removed() {
  return 7203;
}
